### ISSUE TITLE
Improve article 1604.00801

### ISSUE THREAD

**Issue by jfine2358** [dginev/ar5iv#349]
# Exact location of issue

https://arxiv.org/abs/1604.00801
https://ar5iv.labs.arxiv.org/html/1604.00801
https://ar5iv.labs.arxiv.org/log/1604.00801

This arises from #347. I used the https://ar5iv.labs.arxiv.org/feeling_lucky to retrieve this article.

I report 1 * 2 + 1 * 15 = 17 issues. (One issue twice, one issue five times). For clarity, this is for information only. I'm not requesting that these issues be fixed.

1. Info:misdefined:utf-8 input isn't valid under encoding utf-8
* at 1604.00801.tex; line 1049 col 0 - line 1049 col 0
* at 1604.00801.tex; line 1083 col 0 - line 1083 col 0

2. Warning:not_parsed:[details] MathParser failed (15 occurrences). This first such is
```
at 1604.00801.tex; line 281 col 4 - line 281 col 4
 In "$\displaystyle\mathcal{N}_{\lambda}:=\{w\in X_{0}:\phi_{w}^{\prime}(t)=\langle J^{\prime}_{\lambda}(w),w\rangle=0\}\@@ENDINLINEMATH"
 N[[UNKNOWN]] _{\lambda}[[POSTSUBSCRIPT]]
  > :[[METARELOP]] =[[RELOP]] \{[[OPEN]] w[[UNKNOWN]] ∈[[RELOP]] X[[UNKNOWN]] _{0}[[POSTSUBSCRIPT]] :[[METARELOP]] ϕ[[UNKNOWN]] _{w}[[POSTSUBSCRIPT]] ^{\prime}[[POSTSUPERSCRIPT]] ([[OPEN]] t[[UNKNOWN]] )[[CLOSE]] =[[RELOP]] \langle[[OPEN]] J[[UNKNOWN]] ^{\prime}[[POSTSUPERSCRIPT]] _{\lambda}[[POSTSUBSCRIPT]] ([[OPEN]] w[[UNKNOWN]] )[[CLOSE]] ,[[PUNCT]] w[[UNKNOWN]] \rangle[[CLOSE]] =[[RELOP]] 0[[NUMBER]] \}[[CLOSE]]
```

# Further information

Python fails to read file as Unicode.
```python
>>> lines = [l for l in open('pfracsingular.tex')] 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 8021: invalid continuation byte
```
Here's the first occurence of the offending byte. It occurs on line 1049.
```python
>>> data = open('pfracsingular.tex', 'rb').read()
>>> data[73557-30:73557 + 30]
b'erm}, C. R. Acad. Sci. Paris S\xe9r. I, 338 (2004) 831-836.\r\n\r\n'
>>> data = open('pfracsingular.tex', 'rb').read()
>>> bbb = bytes.fromhex('e9')
>>> data.find(bbb)
73557
>>> data[73557-30:73557 + 30]
b'erm}, C. R. Acad. Sci. Paris S\xe9r. I, 338 (2004) 831-836.\r\n\r\n'
>>> 
```

In the LaTeX file it shows itself as [copy and paste, wrapping added]
```latex
\bibitem{gr1} M. Ghergu and V. R\v{a}dulescu, {\it Bifurcation for 
a class of singular elliptic problems with quadratic convection term}, 
C. R. Acad. Sci. Paris Sér. I, 338 (2004) 831-836.
```

In the HTML we have [copy and paste, wrapping added]
```
M. Ghergu and V. Rǎdulescu, Bifurcation for a class of singular elliptic problems
with quadratic convection term, C. R. Acad. Sci. Paris S r. I, 338
(2004) 831-836. 
```

In the PDF we have [copy and paste, wrapping added]
```
M. Ghergu and V. Rˇadulescu, Bifurcation for a class of singular elliptic problems 
with quadratic convection term, C. R. Acad. Sci. Paris Sr. I, 338
(2004) 831-836.
```

**Comment by dginev** [comment]
1. Interesting. The HTML outputs `S r` instead of `Sér`, which is one encoding issue to look into.

2. As to the math example, the raw formula parses in isolation in latexml, so it is also curious. It appears that the ligature connecting `:` and `=` into `:=` did not activate during tokenization here. Worth checking why not.
